### ISSUE TITLE
AP regression from new release in Loader 0.14.15

### ISSUE THREAD

**Issue by zml2008** [FabricMC/Mixin#107]
I've got [an accessor](https://github.com/KyoriPowered/adventure-platform-fabric/blob/563db62e608038d15d83178a18bc3735b05afb1b/src/accessor/java/net/kyori/adventure/platform/fabric/impl/accessor/api/key/InvalidKeyExceptionAccess.java#L33) targeting [a class in my own API library](https://github.com/KyoriPowered/adventure/blob/a79cef4e49575551c6eb39ad09df1e674e11b6b7/key/src/main/java/net/kyori/adventure/key/InvalidKeyException.java#L39) that is non-obf. This accessor has been compiling and applying fine in past versions, but with this new Mixin version (0.12.3?) I get the following compile error:

```
C:\Users\abby\dev\kyori-text\adventure-platform-fabric\src\accessor\java\net\kyori\adventure\platform\fabric\impl\accessor\api\key\InvalidKeyExceptionAccess.java:34: error: Invalid Factory @Invoker return type, expected null but found net.kyori.adventure.key.InvalidKeyException
  @Invoker(value = "<init>", remap = false)
  ^
```

I have tried adding `remap = false` to avoid the error, but it has had no effect.

**Comment by LlamaLad7** [comment]
Seems to be another case of mixin randomly using mirror instead of its own abstractions that I missed in the PR. Will fix later today.
See [here](https://github.com/FabricMC/Mixin/blob/6d715f2f58ed394469402def196559149d873dbf/src/ap/java/org/spongepowered/tools/obfuscation/AnnotatedMixinElementHandlerAccessor.java#L307).

**Comment by zml2008** [comment]
thanks llama <3
