### ISSUE TITLE
Allow cancellation in constructors

### ISSUE THREAD

**Issue by mpfaff** [FabricMC/Mixin#125]
[This commit](https://github.com/FabricMC/Mixin/commit/536170a94675b07e462cc46cdb6493586bdd6dcc) introduced support for injecting into constructors, but added a restriction that cancellation was forbidden.

What was the rationale behind this? Is the concern that developers would cancel before the call to the `super` constructor? Any argument in favour of this mandatory restriction is reflective of a "we know best" attitude that is disappointing from a project that purports to give developers freedom to change the game how they see fit.

There are legitimate cases where this restriction gets in the way. If safety is such a concern, perhaps there should be a check for a cancellable injection specifically *before* the call to `super`. But putting that aside, the restriction as currently implemented should be, at most, an optional, on-by-default restriction that can be disabled via an option in `mod.mixins.json`.

Edit: Let me add that if you are willing to accept a PR loosening this restriction, with or without a check for cancellations before the call to `super`, I would be happy to take a crack at it.

**Comment by IMS212** [comment]
Cancelling a constructor breaks many rules IIRC, including having unset final fields.

**Comment by LlamaLad7** [comment]
There should be no reason ever to cancel a constructor. If you think you need it then ask in the discord because I guarantee there will be a more sensible way to achieve your goal.

**Comment by mpfaff** [comment]
@IMS212 
> Cancelling a constructor breaks many rules IIRC, including having unset final fields.

Not necessarily. The cancellation can occur after field initialization is complete, or the fields can be initialized in the injected method.

@LlamaLad7 
> There should be no reason ever to cancel a constructor. If you think you need it then ask in the discord because I guarantee there will be a more sensible way to achieve your goal.

Once again, this attitude does not respect the developers using mixins. As an aside, I would really appreciate it if people who develop or otherwise know a lot about Mixins put their effort into improving the documentation rather than answering questions in discord that are impossible for search engines to index.

**Comment by LlamaLad7** [comment]
There are a ton of places in Mixin that are deliberately restrictive to stop bad things happening, and this is just one of them. Lifting it without introducing footguns would require a lot of complex analysis.
> or the fields can be initialized in the injected method.

e.g. no, the JVM requires that final fields are only written to from `<init>` itself, and an `Inject` adds a call to a separate handler method that would not be enough to appease the verifier. It would require making them non-final and thereby preventing the JIT from performing some of its optimisations.
There are always other options like just allocating an instance with `Unsafe` and initialising however you want. 
The reason so much happens on discord is because mixins are incredibly nuanced and there are always many different ways to achieve the same thing, and it's only possible to differentiate them if you know the ins and outs of them all. As a newcomer to mixin if you see something in the docs like "how to replace a method call", and you just want to change an argument, the tendency is to think "oh yeah that would work" and jump into writing incompatible/brittle mixins. That said I've had a vague plan for quite a while to write an exhaustive tutorial that would take you through each injector and when to / not to use it, but that's a very big task and I have a lot of other things on the go. In the meantime do come talk to us, you'll normally get an answer fairly quickly and the best way to learn mixins is by talking about them against a particular use-case.

**Comment by mpfaff** [comment]
> e.g. no, the JVM requires that final fields are only written to from `<init>` itself, and an `Inject` adds a call to a separate handler method that would not be enough to appease the verifier. It would require making them non-final and thereby preventing the JIT from performing some of its optimizations.

Fair point. I do think it would be ideal if the injected method were inlined, making that a non-issue, but I understand that would probably be difficult to implement correctly.

> There are always other options like just allocating an instance with Unsafe and initializing however you want.

I hadn't considered that. I'll keep it in mind in the future (although I will avoid using it where possible).

> That said I've had a vague plan for quite a while to write an exhaustive tutorial that would take you through each injector and when to / not to use it

I (and I'm sure many others) would appreciate that, but I think it's best not to think of it as one huge task to complete at once. Short notes sprinkled throughout the documentation would add up over time.

I've worked around my particular use case for this by now, though not in the most ideal way if I recall correctly. I will close this issue now, but if I encounter a situation similar to this in the future and come up with a good solution, I might come back and leave a comment just to point others in the right direction.
